defaults: &defaults
  autocreate_indexes: true

development:
  host: localhost
  database: thingslist_development

test:
  host: localhost
  database: thingslist_test

# set these environment variables on your prod server
production:
  uri: mongodb://heroku:heroku1234@ds031867.mongolab.com:31867/thingslist
  #uri: <%= ENV['MONGOHQ_URL'] %>

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
